version: "3.9"

# 在此處設置全局日誌驅動程式
x-logging: &logging
  driver: "json-file"
  options:
    max-size: "3m" # 這裡設定最大大小為 5MB
    max-file: "2" # 這裡設定最大文件數為 3

x-base_service: &base
  image: twitch-recorder:v1
  # build: .
  command: python3 twitch-recorder.py
  restart: always
  # logging: *logging
  environment:
    - LC_ALL=C.UTF-8
  volumes:
    - .:/app
  # healthcheck:
  #   test: ["CMD", "supervisorctl", "status"]
  #   interval: 60s
  #   timeout: 3s
  #   retries: 1

services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8892:8080

  remiiouo:
    <<: *base
    environment:
      - displayname=小米
      - username=remiiouo

  abuy_:
    <<: *base
    environment:
      - displayname=小白
      - username=abuy_

  monpo147:
    <<: *base
    environment:
      - displayname=孟婆
      - username=monpo147

  leebabyadmain:
    <<: *base
    environment:
      - displayname=大魯味
      - username=leebabyadmain

  qaws_1109:
    <<: *base
    environment:
      - displayname=凌晨
      - username=qaws_1109

  yrchang_:
    <<: *base
    environment:
      - displayname=小九九
      - username=yrchang_

  god_lita:
    <<: *base
    environment:
      - displayname=韓妹123
      - username=god_lita

  woohankyung:
    <<: *base
    environment:
      - displayname=韓妹韓剛
      - username=woohankyung

  som0322:
    <<: *base
    environment:
      - displayname=韓妹som
      - username=som0322

  
  gyu_0227:
    <<: *base
    environment:
      - displayname=韓妹
      - username=gyu_0227

  golaniyule0:
    <<: *base
    environment:
      - displayname=韓妹麋鹿
      - username=golaniyule0

  pikapikalove05:
    <<: *base
    environment:
      - displayname=韓妹害羞
      - username=pikapikalove05

  yoon_froggy:
    <<: *base
    environment:
      - displayname=韓妹
      - username=yoon_froggy

  magenta62:
    <<: *base
    environment:
      - displayname=韓妹
      - username=magenta62

  0cheoli:
    <<: *base
    environment:
      - displayname=韓妹re
      - username=0cheoli

  yoloiiiooo:
    <<: *base
    environment:
      - displayname=余家儀
      - username=yoloiiiooo

  lyasyaa:
    <<: *base
    environment:
      - displayname=莫斯科
      - username=lyasyaa

  fasoollka:
    <<: *base
    environment:
      - displayname=俄羅斯
      - username=fasoollka

  kaoyunhsin:
    <<: *base
    environment:
      - displayname=雞肉披薩
      - username=kaoyunhsin

  rock1020520:
    <<: *base
    environment:
      - displayname=靜芳
      - username=rock1020520

  ycc3741:
    <<: *base
    environment:
      - displayname=外神歪西
      - username=ycc3741

  57ye777:
    <<: *base
    environment:
      - displayname=舞痴戶外
      - username=57ye777

  57re777:
    <<: *base
    environment:
      - displayname=舞痴室內
      - username=57re777

  haley__13:
    <<: *base
    environment:
      - displayname=海莉兒
      - username=haley__13

  noe_147:
    <<: *base
    environment:
      - displayname=諾伊
      - username=noe_147

  shao0621:
    <<: *base
    environment:
      - displayname=玉子燒燒燒
      - username=shao0621

  yunzzh_:
    <<: *base
    environment:
      - displayname=暈針
      - username=yunzzh_

  ayuan919:
    <<: *base
    environment:
      - displayname=阿媛
      - username=ayuan919

  neineimeme:
    <<: *base
    environment:
      - displayname=捏寧
      - username=neineimeme

  honeyliciousss:
    <<: *base
    environment:
      - displayname=天菜
      - username=honeyliciousss

  discat_14:
    <<: *base
    environment:
      - displayname=小荻
      - username=discat_14

  cinnazoll:
    <<: *base
    environment:
      - displayname=喜拿柔
      - username=cinnazoll

  appl55661022:
    <<: *base
    environment:
      - displayname=小沁子
      - username=appl55661022

  nurockplayer:
    <<: *base
    environment:
      - displayname=塔奇巧克力
      - username=nurockplayer

  neun09:
    <<: *base
    environment:
      - displayname=傑洛奈
      - username=neun09

  # 0_0tjh:
  #   <<: *base
  #   environment:
  #     - displayname=米朵粒小姐姐
  #     - username=0_0tjh

  hxxhxx2001:
    <<: *base
    environment:
      - displayname=海小熊
      - username=hxxhxx2001

  sj556634:
    <<: *base
    environment:
      - displayname=賓漢
      - username=sj556634

  littleblue_om:
    <<: *base
    environment:
      - displayname=小藍
      - username=littleblue_om

  # ririii1231:
  #   <<: *base
  #   environment:
  #     - displayname=梨梨子
  #     - username=ririii1231

  imuuuu_:
    <<: *base
    environment:
      - displayname=魚魚系
      - username=imuuuu_

  yujuu623:
    <<: *base
    environment:
      - displayname=右汝
      - username=yujuu623
  iris920123:
    <<: *base
    environment:
      - displayname=小有
      - username=iris920123

  yukineko0975:
    <<: *base
    environment:
      - displayname=雪貓
      - username=yukineko0975

  ciao_1208:
    <<: *base
    environment:
      - displayname=陳孟蕎
      - username=ciao_1208

  tsuruaoi:
    <<: *base
    environment:
      - displayname=鶴葵
      - username=tsuruaoi

  m092230:
    <<: *base
    environment:
      - displayname=庭米
      - username=m092230

  nai0529:
    <<: *base
    environment:
      - displayname=奈兒
      - username=nai0529

  nayabnb:
    <<: *base
    environment:
      - displayname=嫩嫩の
      - username=nayabnb

  # starstar2012:
  #   <<: *base
  #   environment:
  #     - displayname=星星子
  #     - username=starstar2012

  kammeicamey:
    <<: *base
    environment:
      - displayname=錦美
      - username=kammeicamey

  yiyue1229:
    <<: *base
    environment:
      - displayname=海豹
      - username=yiyue1229

  chungchung030:
    <<: *base
    environment:
      - displayname=蔥爺是也
      - username=chungchung030

  happycatmimi:
    <<: *base
    environment:
      - displayname=魔理花是魔魔醬
      - username=happycatmimi

  sandwichwx3:
    <<: *base
    environment:
      - displayname=我是三角錐
      - username=sandwichwx3
      - quality=720p

  tonychachachacha:
    <<: *base
    environment:
      - displayname=基隆東
      - username=tonychachachacha

  # rinchengg:
  #   <<: *base
  #   environment:
  #     - displayname=AVA
  #     - username=rinchengg

  # jd_onlymusic:
  #   <<: *base
  #   environment:
  #     - displayname=台北建東
  #     - username=jd_onlymusic

  # small_fat0810:
  #   <<: *base
  #   environment:
  #     - displayname=我是小胖777
  #     - username=small_fat0810

  # taiwanmeme:
  #   <<: *base
  #   environment:
  #     - displayname=台灣迷因
  #     - username=taiwanmeme


  # # 很少開台
  zc7__:
    <<: *base
    environment:
      - displayname=思琪47
      - username=zc7__

  happlesim:
    <<: *base
    environment:
      - displayname=好狗
      - username=happlesim
      - refresh=600

  r_1_1111:
    <<: *base
    environment:
      - displayname=桃園娜美
      - username=r_1_1111
      - refresh=600

  chiehhh0528:
    <<: *base
    environment:
      - displayname=長腿阿姨
      - username=chiehhh0528
      - refresh=600

  # 沒在開台 
  cafedad2:
    <<: *base
    environment:
      - displayname=蚊仔君
      - username=cafedad2
      - refresh=600

  xiaojie1218:
    <<: *base
    environment:
      - displayname=小潔1218
      - username=xiaojie1218
      - refresh=600

  1020yusin:
    <<: *base
    environment:
      - displayname=噗嚕噗嚕噗嚕
      - username=1020yusin
      - refresh=600

  cherry_517:
    <<: *base
    environment:
      - displayname=茄莉
      - username=cherry_517
      - refresh=600

  kate_1224:
    <<: *base
    environment:
      - displayname=瘋狗莉
      - username=kate_1224
      - refresh=600

  eny1ng:
    <<: *base
    environment:
      - displayname=eny1ng
      - username=eny1ng
      - refresh=600

  ximilu0416:
    <<: *base
    environment:
      - displayname=熙米露
      - username=ximilu0416
      - refresh=600

  millyyuu:
    <<: *base
    environment:
      - displayname=米粒米粒米粒
      - username=millyyuu
      - refresh=600

  sandyhwa:
    <<: *base
    environment:
      - displayname=sandyhwa
      - username=sandyhwa
      - refresh=600

  zai116090:
    <<: *base
    environment:
      - displayname=吉兒_
      - username=zai116090
      - refresh=600

  fafaa728:
    <<: *base
    environment:
      - displayname=李花
      - username=fafaa728
      - refresh=600

  rru0fu6:
    <<: *base
    environment:
      - displayname=豬蹄妖精
      - username=rru0fu6
      - refresh=600

  kittiemeowmii:
    <<: *base
    environment:
      - displayname=愷蒂喵
      - username=kittiemeowmii
      - refresh=600

  chiao622:
    <<: *base
    environment:
      - displayname=阿寧
      - username=chiao622
      - refresh=600

  ritsuka131711:
    <<: *base
    environment:
      - displayname=稀飯
      - username=ritsuka131711
      - refresh=600

  mitaliang:
    <<: *base
    environment:
      - username=mitaliang
      - refresh=600

# start cmd /k "cd twitch-stream-recorder-master && python twitch-recorder.py -u happlesim"
